IpsWeb/IpsWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', auth_views.LogoutView.as_view()),
    path('register', views.register, name='register'),
    path('signup/',views.signup,name='signup'),
    path('camas/', views.camas,name='camas'),
    path('oxigeno/', views.oxigeno, name='oxigeno'),
    path('foro/', views.foro , name='foro'),
    path('departamento/', views.departamento, name='departamento'),
    path('provincia/', views.provincia, name="provincia"),
    path('distrito/',views.distrito, name='distrito'),
]

IpsWeb/usuarios/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class ForoComentario(models.Model):
    idcom = models.AutoField(db_column='IDCom', primary_key=True)  # Field name made lowercase.
    comusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='ComUsuCod')  # Field name made lowercase.
    comidpro = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ComIdPro')  # Field name made lowercase.
    comdes = models.TextField(db_column='ComDes')  # Field name made lowercase.
    comtip = models.IntegerField(db_column='ComTip')  # Field name made lowercase.
    comvis = models.IntegerField(db_column='ComVis')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'foro_comentario'
        unique_together = (('idcom', 'comusucod', 'comidpro'),)


class Hospital(models.Model):
    hoscod = models.AutoField(db_column='HosCod', primary_key=True)  # Field name made lowercase.
    hosnom = models.CharField(db_column='HosNom', max_length=40)  # Field name made lowercase.
    hostipo = models.CharField(db_column='HosTipo', max_length=40)  # Field name made lowercase.
    hoscama = models.IntegerField(db_column='HosCama')  # Field name made lowercase.
    hosdispo = models.IntegerField(db_column='HosDispo')  # Field name made lowercase.
    hoszonid = models.CharField(db_column='HosZonId', max_length=8)  # Field name made lowercase.
    hosusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='HosUsuCod')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'hospital'
        unique_together = (('hoscod', 'hosusucod'),)


class Producto(models.Model):
    idpro = models.IntegerField(db_column='IdPro', primary_key=True)  # Field name made lowercase.
    pronom = models.CharField(db_column='ProNom', max_length=40)  # Field name made lowercase.
    prodis = models.IntegerField(db_column='ProDis')  # Field name made lowercase.
    procant = models.IntegerField(db_column='ProCant')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'producto'

class Proveedor(models.Model):
    provecod = models.AutoField(db_column='ProveCod', primary_key=True)  # Field name made lowercase.
    provenom = models.CharField(db_column='ProveNom', max_length=40)  # Field name made lowercase.
    proveidpro = models.ForeignKey(Producto, models.DO_NOTHING, db_column='ProveIdPro')  # Field name made lowercase.
    proveusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='ProveUsuCod')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'proveedor'
        unique_together = (('provecod', 'proveidpro', 'proveusucod'),)


class Usuario(models.Model):
    usucod = models.AutoField(db_column='UsuCod', primary_key=True)  # Field name made lowercase.
    usunom = models.CharField(db_column='UsuNom', max_length=40)  # Field name made lowercase.
    usuape = models.CharField(db_column='UsuApe', max_length=40)  # Field name made lowercase.
    usuzon = models.CharField(db_column='UsuZon', max_length=8)  # Field name made lowercase.
    usutel = models.IntegerField(db_column='UsuTel')  # Field name made lowercase.
    usudir = models.CharField(db_column='UsuDir', max_length=40)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'usuario'
        unique_together = (('usucod'),)

class Departamento(models.Model):
    depcod = models.IntegerField(db_column='DepCod', primary_key=True)
    depnom = models.CharField(db_column='DepNom', max_length=40)
    
    def __str__(self):
        return self.depnom+""
    

    class Meta:
        db_table = 'departamento'
        unique_together = (('depcod'),)

class Provincia(models.Model):
    procod = models.IntegerField(db_column='ProCod', primary_key=True)
    pronom = models.CharField(db_column='ProNom', max_length=40)
    prodepcod = models.ForeignKey('Departamento',models.DO_NOTHING, db_column='ProDepCod')

    def __str__(self):
        return self.pronom+""
    
    class Meta:
        managed = False
        db_table = 'provincia'
        unique_together = (('procod','prodepcod'),)

class Distrito(models.Model):
    discod = models.IntegerField(db_column='DisCod', primary_key=True)
    disnom = models.CharField(db_column='DisNom', max_length=40)
    disprocod = models.ForeignKey('Provincia',models.DO_NOTHING, db_column='DisProCod')

    class Meta:
        managed = False
        db_table = 'distrito'
        unique_together = (('discod','disprocod'),)

IpsWeb/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Healthy Peru - Foro</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap" rel="stylesheet">

    <!--

Template 2098 Health

http://www.tooplate.com/view/2098-health

-->
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="Tooplate">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="stylesheet" href="css/animate.css">
<link rel="stylesheet" href="css/owl.carousel.css">
<link rel="stylesheet" href="css/owl.theme.default.min.css">

<!-- MAIN CSS -->
<link rel="stylesheet" href="css/tooplate-style.css">

</head>

<body>
     <!-- HEADER -->

     <!-- MENU -->
     <section class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">

             <div class="navbar-header">
                  <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                  </button>

                  <!-- lOGO TEXT HERE -->
                  <a href="index.html" class="navbar-brand"><i class="fa fa-h-square"></i>ealth Perú</a>
             </div>

             <!-- MENU LINKS -->
             <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav navbar-right">
                       <li><a href="index.html" class="smoothScroll">Inicio</a></li>
                       <li><a href="camas.html" class="smoothScroll">Camas UCI</a></li>
                       <li><a href="oxigeno.html" class="smoothScroll">Recarga de balones de Oxigeno</a></li>                         
                       <li><a href="detail.html" class="smoothScroll">Foro</a></li>
                       <li><a href="#contactanos" class="smoothScroll">Contactanos</a></li>
                       <li class="appointment-btn"><a href="indexout.html">Cerrar Sesion</a></li>
                  </ul>
             </div>

        </div>
   </section>

        <!--Topic Section-->
        <div class="topic-container">
            <!--Original thread-->
            <div class="head">
                <div class="authors">DA UNA MANO- FORO DE AYUDA</div>
                <div class="content">Recuerda mantener el respeto para todas las personas.</div>
            </div>
            
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">Diana Lizeth</a></div>
                    <div>Role</div>
                    <img src="https://img.europapress.es/fotoweb/fotonoticia_20200306100151_420.jpg" alt="" >
                    <div>Posts: <u>1</u></div>
                    <div>Points: <u>3</u></div>
                </div>
                <div class="content">
                    Un saludo coordial, deseando lo mejor para todas las familias en esta epoca tan dificil.
                    <br>Escribo para solicitar 5 balones de oxigeno debido a que toda mi familia se ha visto afectada por la pandemia.
                    <br><br> De poder brindarme ayuda porfavor llamar al numero 952 123 659.
                    Gracias y que Dios los bendiga.
                    <br>
                    <hr>
                    Regards username
                    <br>
                    <div class="comment">
                        <button onclick="showComment()">Comment</button>
                    </div>
                </div>
            </div>
        </div>

        <!--Comment Area-->
        <div class="comment-area hide" id="comment-area">
            <textarea name="comment" id="" placeholder="comment here ... "></textarea>
            <input type="submit" value="submit">
        </div>

        <!--Comments Section-->
        <div class="comments-container">
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">Lorenzo Pedro</a></div>
                    <div>Role</div>
                    <img src="https://www.latercera.com/resizer/7d2vNG2ckpPkztSuHKhjTLfIomM=/380x570/smart/arc-anglerfish-arc2-prod-copesa.s3.amazonaws.com/public/BQWEY4OYS5CLNNJDVZSL2XXRT4.jpg" alt="">
                    <div>Posts: <u>3</u></div>
                    <div>Points: <u>2</u></div>
                </div>
                <div class="content">
                    Un saludo. Recientemente uno de mis hermanos se enfermo pero felizmente pudo recuperarse, por ello dispongo de 2 balones de oxigeno.
                    <br>Por favor de necesitarlos contactar con el numero : 911 100 200.
                    <br><br>
                    Gracias y bendiciones para todos.
                    <br>
                    <br>
                    <div class="comment">
                        <button onclick="showReply()">Reply</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Reply Area-->
        <div class="comment-area hide" id="reply-area">
            <textarea name="reply" id="" placeholder="reply here ... "></textarea>
            <input type="submit" value="submit">
        </div>


        <!--Another Comment With replies-->
        <div class="comments-container">
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">Yaki Salas</a></div>
                    <div>Role</div>
                    <img src="https://i.pinimg.com/originals/18/23/6c/18236c122583aa65cece65c1f9107449.jpg" alt="">
                    <div>Posts: <u>1</u></div>
                    <div>Points: <u>1</u></div>
                </div>
                <div class="content">
                    Un saludo para todos.
                    <br>Con motivo de brindar ayuda en estos tiempos tan dificiles, mi familia compro 5 balones de oxigeno que seran donados.
                    <br><br>Para mayor informacion escribirme o llamar al numero : 957 147 258
                    Bendiciones para todos. 
                    <br>
                    <br>
                    <div class="comment">
                        <button onclick="showReply()">Reply</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Reply Area-->
        <div class="comment-area hide" id="reply-area">
            <textarea name="reply" id="" placeholder="reply here ... "></textarea>
            <input type="submit" value="submit">
        </div>

        

    </div>
   
    <script src="js/main.js"></script>
</body>
</html>

IpsWeb/templates/forums.html

{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

     <title>HEALTHY PERÚ | Camas UCI</title>
<!--

Template 2098 Health

http://www.tooplate.com/view/2098-health

-->
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="Tooplate">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="{% static 'css/btn-log-google.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

     <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">



</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">


     <!-- HEADER -->
     <!-- MENU -->
     <section class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="index.html" class="navbar-brand"><i class="fa fa-h-square"></i>ealth Perú</a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                         <li><a href="index.html" class="smoothScroll">Inicio</a></li>
                         <li><a href="/camas/" class="smoothScroll">Camas UCI</a></li>
                         <li><a href="/oxigeno/" class="smoothScroll">Recarga de balones de Oxigeno</a></li>                         
                         <li><a href="#appointment" class="smoothScroll">Foro</a></li>
                         <li><a href="#contactanos" class="smoothScroll">Contactanos</a></li>
                         {% if user.is_authenticated %}
                         <li class="appointment-btn"><a href="accounts/logout">Cerrar Sesión</a></li>
                         <li><a href="#">{{ user.first_name }}</a></li>
                         {% else %}
                         <li class="appointment-btn"><a href="/accounts/login">Ingresar</a> </li>
                         {% endif %}
                    </ul>
               </div>

          </div>
     </section>
    <section class="foro">
        
        <div class="container">
            <h2 style="color:brown">FORO - DA UNA MANO</h2>

            <div class="subforum">
                <div class="subforum-title">
                    <h2>CAMAS UCI</h2>
                </div>
                <div class="subforum-row alert alert-success">
                    <div class="subforum-icon subforum-column center">
                        <img src="https://www.212asesores.com/wp-content/uploads/2018/10/seguros-de-salud-icono-1-300x237.png" width="60" height="50" />
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="#">DONACIONES</a></h4>
                        <p>En este apartado podra acceder a comentarios de personas que brindan ayuda en la donacion de una Cama UCI.</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>24 Posts | 12 Topics</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        <b><a href="">Ultima publicacion</a></b> by <a href="">Romina Lopez Arce</a> 
                        <br>on <small>22 07 2021</small>
                    </div>
                </div>
                <div class="subforum-row alert alert-danger">
                    <div class="subforum-icon subforum-column center">
                        <img src="https://www.212asesores.com/wp-content/uploads/2018/10/seguros-de-salud-icono-1-300x237.png" width="60" height="50" />
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="#">SOLICITUDES</a></h4>
                        <p>En este apartado podra acceder a comentarios de personas que realizan una solicitud de Cama UCI.</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>22 Posts | 10 Topics</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        <b><a href="">Ultima publicacion</a></b> by <a href="">Delia Paola Puma</a> 
                        <br>on <small>17 07 2021</small>
                    </div>
                </div>
            </div>
            
            <!--More-->
            
            
            <div class="subforum">
                <div class="subforum-title">
                    <h2>BALONES DE OXIGENO</h2>
                </div>
                <div class="subforum-row alert alert-success">
                    <div class="subforum-icon subforum-column center">
                        <img src="https://www.212asesores.com/wp-content/uploads/2018/10/seguros-de-salud-icono-1-300x237.png" width="60" height="50" />
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="#">DONACIONES</a></h4>
                        <p>En este apartado podra acceder a publicaciones de personas que brindan donaciones de balones de oxigeno..</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>2 Posts | 10 Topics</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        <b><a href="">Last post</a></b> by <a href="">Julia Miriam Diaz</a> 
                        <br>on <small>19 07 2021</small>
                    </div>
                </div>
                <hr class="subforum-devider">
                <div class="subforum-row alert alert-danger">
                    <div class="subforum-icon subforum-column center">
                        <img src="https://www.212asesores.com/wp-content/uploads/2018/10/seguros-de-salud-icono-1-300x237.png" width="60" height="50" />
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="#">SOLICITUDES</a></h4>
                        <p>En este apartado podra acceder a publicaciones de personas que solicitan balones de oxigeno..</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>24 Posts | 12 Topics</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        <b><a href="">Last post</a></b> by <a href="">Alex Fernando de la Fuente.</a> 
                        <br>on <small>19 07 2021</small>
                    </div>
                </div>
                <hr class="subforum-devider">
                
            
            <div class="subforum">
                <div class="subforum-title">
                    <h1>AYUDA-INFORMACION</h1>
                </div>
                <div class="subforum-row">
                    <div class="subforum-icon subforum-column center">
                        <img src="https://www.212asesores.com/wp-content/uploads/2018/10/seguros-de-salud-icono-1-300x237.png" width="60" height="50" />
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="#">Tips para realizar una publicacion</a></h4>
                        <p>En este apartado podra encontrar recomendaciones para realizar una buena publicacion</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>24 Posts | 12 Topics</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        <b><a href="">Last post</a></b> by <a href="">Agustina Dayana Molina</a> 
                        <br>on <small>21 07 2021</small>
                    </div>
                </div>
                <hr class="subforum-devider">
                
               
            </div>
            <!---->
        </div>
    
        <!-- Forum Info -->
        <script src="js/main.js"></script>
    </section>

     <!-- SCRIPTS -->
     <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/jquery.sticky.js' %}"></script>
     <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
     <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
     <script src="{% static 'js/magnific-popup-options.js' %}"></script>
     <script src="{% static 'js/wow.min.js' %}"></script>
     <script src="{% static 'js/smoothscroll.js' %}"></script>
     <script src="{% static 'js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

IpsWeb/templates/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title></title> 
	<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=3.0, minimum-scale=1.0">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
	

</head>  
<body class="body" style="background: url('{% static '/img/loginImagen.jpeg' %}');">
 <form class="formulario" method="POST", action="register">
    
    <h1>Registrar datos adicionales</h1>
    {% csrf_token %}
     <div class="contenedor">
     
        <div class="input-contenedor">
            <i class="fas fa-user icon"></i>
            <input id="id_usunom" name="usunom" type="text" placeholder="Nombre">
         </div>

         <div class="input-contenedor">
            <i class="fas fa-user icon"></i>
            <input id="id_usuape" name="usuape" type="text" placeholder="Apellido">
         </div>

         <div class="input-contenedor">
            <i class="fas fa-user icon"></i>
            <input id="id_usuzon" name="usuzon" type="text" placeholder="Ubicacion Ubiego">
         </div>
         
         <div class="input-contenedor">
            <i class="fas fa-user icon"></i>
            <input id="id_usutel" name="usutel" type="text" placeholder="Telefono">
         </div>

         <div class="input-contenedor">
            <i class="fas fa-user icon"></i>
            <input id="id_usudir" name="usudir" type="text" placeholder="Dirección">
         </div>

         <input type="submit" value="Registrate" class="button">
         
        </div>
    </form>
</body>
</html>