IpsWeb/IpsWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', auth_views.LogoutView.as_view()),
    path('register', views.register, name='register'),
    path('signup/',views.signup,name='signup'),
    path('camas/', views.camas,name='camas'),
    path('oxigeno/', views.oxigeno, name='oxigeno'),
    path('foro/', views.foro , name='foro'),
    path('departamento/', views.departamento, name='departamento'),
    path('provincia/', views.provincia, name="provincia"),
    path('distrito/',views.distrito, name='distrito'),
]

IpsWeb/usuarios/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class ForoComentario(models.Model):
    idcom = models.AutoField(db_column='IDCom', primary_key=True)  # Field name made lowercase.
    comusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='ComUsuCod')  # Field name made lowercase.
    comidpro = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ComIdPro')  # Field name made lowercase.
    comdes = models.TextField(db_column='ComDes')  # Field name made lowercase.
    comtip = models.IntegerField(db_column='ComTip')  # Field name made lowercase.
    comvis = models.IntegerField(db_column='ComVis')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'foro_comentario'
        unique_together = (('idcom', 'comusucod', 'comidpro'),)


class Hospital(models.Model):
    hoscod = models.AutoField(db_column='HosCod', primary_key=True)  # Field name made lowercase.
    hosnom = models.CharField(db_column='HosNom', max_length=40)  # Field name made lowercase.
    hostipo = models.CharField(db_column='HosTipo', max_length=40)  # Field name made lowercase.
    hoscama = models.IntegerField(db_column='HosCama')  # Field name made lowercase.
    hosdispo = models.IntegerField(db_column='HosDispo')  # Field name made lowercase.
    hoszonid = models.CharField(db_column='HosZonId', max_length=8)  # Field name made lowercase.
    hosusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='HosUsuCod')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'hospital'
        unique_together = (('hoscod', 'hosusucod'),)


class Producto(models.Model):
    idpro = models.IntegerField(db_column='IdPro', primary_key=True)  # Field name made lowercase.
    pronom = models.CharField(db_column='ProNom', max_length=40)  # Field name made lowercase.
    prodis = models.IntegerField(db_column='ProDis')  # Field name made lowercase.
    procant = models.IntegerField(db_column='ProCant')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'producto'

class Proveedor(models.Model):
    provecod = models.AutoField(db_column='ProveCod', primary_key=True)  # Field name made lowercase.
    provenom = models.CharField(db_column='ProveNom', max_length=40)  # Field name made lowercase.
    proveidpro = models.ForeignKey(Producto, models.DO_NOTHING, db_column='ProveIdPro')  # Field name made lowercase.
    proveusucod = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='ProveUsuCod')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'proveedor'
        unique_together = (('provecod', 'proveidpro', 'proveusucod'),)


class Usuario(models.Model):
    usucod = models.AutoField(db_column='UsuCod', primary_key=True)  # Field name made lowercase.
    usunom = models.CharField(db_column='UsuNom', max_length=40)  # Field name made lowercase.
    usuape = models.CharField(db_column='UsuApe', max_length=40)  # Field name made lowercase.
    usuzon = models.CharField(db_column='UsuZon', max_length=8)  # Field name made lowercase.
    usutel = models.IntegerField(db_column='UsuTel')  # Field name made lowercase.
    usudir = models.CharField(db_column='UsuDir', max_length=40)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'usuario'
        unique_together = (('usucod'),)

class Departamento(models.Model):
    depcod = models.IntegerField(db_column='DepCod', primary_key=True)
    depnom = models.CharField(db_column='DepNom', max_length=40)
    
    def __str__(self):
        return self.depnom+""
    

    class Meta:
        db_table = 'departamento'
        unique_together = (('depcod'),)

class Provincia(models.Model):
    procod = models.IntegerField(db_column='ProCod', primary_key=True)
    pronom = models.CharField(db_column='ProNom', max_length=40)
    prodepcod = models.ForeignKey('Departamento',models.DO_NOTHING, db_column='ProDepCod')

    def __str__(self):
        return self.pronom+""
    
    class Meta:
        managed = False
        db_table = 'provincia'
        unique_together = (('procod','prodepcod'),)

class Distrito(models.Model):
    discod = models.IntegerField(db_column='DisCod', primary_key=True)
    disnom = models.CharField(db_column='DisNom', max_length=40)
    disprocod = models.ForeignKey('Provincia',models.DO_NOTHING, db_column='DisProCod')

    class Meta:
        managed = False
        db_table = 'distrito'
        unique_together = (('discod','disprocod'),)

IpsWeb/templates/ubicacion/departamento.html
{% load bootstrap4 %}

{% bootstrap_css %}

<body>

<section class="container">

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form class="form box" method="POST" action="/departamento/">
                {% csrf_token %}
                <h1>Dapartamentos</h1>
                <div class="form-group">
                    <label for="id_depcod">Código Departamento</label>
                    <input type="text" name="depcod" class="form-control" id="id_depcod" placeholder="codigo">
                </div>

                <div class="form-group">
                    <label for="id_depnom">Nombre Departamento</label>
                    <input type="text" name="depnom" class="form-control" id="id_depnom" placeholder="Nombre">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>


</section>


</body>

IpsWeb/templates/ubicacion/distrito.html
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% bootstrap_css %}

<body>

<section class="container">

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h1>Distritos</h1>
            <form class="form box" method="POST" action="/distrito/">
                {% csrf_token %}

                {{ form|crispy }}
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>


</section>


</body>

IpsWeb/templates/ubicacion/provincia.html
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% bootstrap_css %}

<body>

<section class="container">

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h1>Provincias</h1>
            <form class="form box" method="POST" action="/provincia/">
                {% csrf_token %}

                {{ form|crispy }}
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>


</section>


</body>